// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jkeafhmdkiebqxnmqqcz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImprZWFmaG1ka2llYnF4bm1xcWN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk2MTUzOTEsImV4cCI6MjA1NTE5MTM5MX0.gOhQ3J1Nl-1MjEb81VS8qz-uB7PE-0DcrNRI13IVSME";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);